string stair_id
uint8 UP=1
uint8 DOWN=2
uint8 direction
---
uint8 OK=0
uint8 BUSY=1
uint8 INVALID_GOAL=2
uint8 CAPABILITY_DISABLED=3
uint8 STAIR_FAILED=5
uint8 COMMUNICATION_LOST=8
uint8 result_code
string reason
uint64 ownership_epoch
---
string phase
string detail
